/* This file is auto-generated by SGPT. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sgpt" {
  export interface Resource {
    ANTHROPIC_API_KEY: {
      type: "sgpt.sgpt.Secret"
      value: string
    }
    AUTH_API_URL: {
      type: "sgpt.sgpt.Linkable"
      value: string
    }
    Api: {
      type: "sgpt.cloudflare.Worker"
      url: string
    }
    AuthApi: {
      type: "sgpt.cloudflare.Worker"
      url: string
    }
    AuthStorage: {
      type: "sgpt.cloudflare.Kv"
    }
    BASETEN_API_KEY: {
      type: "sgpt.sgpt.Secret"
      value: string
    }
    Bucket: {
      name: string
      type: "sgpt.cloudflare.Bucket"
    }
    Console: {
      type: "sgpt.cloudflare.SolidStart"
      url: string
    }
    Database: {
      database: string
      host: string
      password: string
      port: number
      type: "sgpt.sgpt.Linkable"
      username: string
    }
    FIREWORKS_API_KEY: {
      type: "sgpt.sgpt.Secret"
      value: string
    }
    GITHUB_APP_ID: {
      type: "sgpt.sgpt.Secret"
      value: string
    }
    GITHUB_APP_PRIVATE_KEY: {
      type: "sgpt.sgpt.Secret"
      value: string
    }
    GITHUB_CLIENT_ID_CONSOLE: {
      type: "sgpt.sgpt.Secret"
      value: string
    }
    GITHUB_CLIENT_SECRET_CONSOLE: {
      type: "sgpt.sgpt.Secret"
      value: string
    }
    GOOGLE_CLIENT_ID: {
      type: "sgpt.sgpt.Secret"
      value: string
    }
    HONEYCOMB_API_KEY: {
      type: "sgpt.sgpt.Secret"
      value: string
    }
    LogProcessor: {
      type: "sgpt.cloudflare.Worker"
    }
    OPENAI_API_KEY: {
      type: "sgpt.sgpt.Secret"
      value: string
    }
    STRIPE_SECRET_KEY: {
      type: "sgpt.sgpt.Secret"
      value: string
    }
    STRIPE_WEBHOOK_SECRET: {
      type: "sgpt.sgpt.Linkable"
      value: string
    }
    Web: {
      type: "sgpt.cloudflare.Astro"
      url: string
    }
    XAI_API_KEY: {
      type: "sgpt.sgpt.Secret"
      value: string
    }
  }
}
/// <reference path="sgpt-env.d.ts" />

import "sgpt"
export {}
